// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWP1nDYlB7T_FzZGjnndz0qPsjjJspXNI',
    appId: '1:543899344931:web:79cd35c62f0abaaf775196',
    messagingSenderId: '543899344931',
    projectId: 'building-mobile-app',
    authDomain: 'building-mobile-app.firebaseapp.com',
    storageBucket: 'building-mobile-app.firebasestorage.app',
    measurementId: 'G-5BJ73L4C76',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xVw-GzrpyucYjX4vwsuhgEXGbwoDsnE',
    appId: '1:543899344931:ios:fd24f6b8133937cd775196',
    messagingSenderId: '543899344931',
    projectId: 'building-mobile-app',
    storageBucket: 'building-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.cliProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7xVw-GzrpyucYjX4vwsuhgEXGbwoDsnE',
    appId: '1:543899344931:ios:fd24f6b8133937cd775196',
    messagingSenderId: '543899344931',
    projectId: 'building-mobile-app',
    storageBucket: 'building-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.cliProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWP1nDYlB7T_FzZGjnndz0qPsjjJspXNI',
    appId: '1:543899344931:web:c18b9c9fdcc150be775196',
    messagingSenderId: '543899344931',
    projectId: 'building-mobile-app',
    authDomain: 'building-mobile-app.firebaseapp.com',
    storageBucket: 'building-mobile-app.firebasestorage.app',
    measurementId: 'G-GZS41TTW77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2lV1DMui7iwPDnbNuYG7mnLTpoXuWvA',
    appId: '1:543899344931:android:20b2d103e3bc4be9775196',
    messagingSenderId: '543899344931',
    projectId: 'building-mobile-app',
    storageBucket: 'building-mobile-app.firebasestorage.app',
  );

}